image: node:16.16.0

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel login -u $VERCEL_ORG_ID -p $VERCEL_API_TOKEN
    - vercel pull --yes --environment=production --token=$VERCEL_API_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_API_TOKEN