trigger:
- main
 
pool:
  name: Azure Pool 
 
jobs:
  - job: vercel-deployment
    inputs:
      vercelProjectId: $(VERCEL_PROJECT_ID)
      vercelOrgId: $(VERCEL_ORG_ID)
      vercelToken: $(VERCEL_API_TOKEN)
      production: true
    displayName: 'Deploy Vercel'