trigger:
  - main
 
pool:
  name: Azure Pool 
 
steps:
  - task: vercel-deployment-task@1
    inputs:
      vercelProjectId: "prj_U2UGGVyxnv23rvllRJ8197UxJPXM"
      vercelOrgId: "team_vUbDpabf52rK5yqVF6hEOS7D"
      vercelToken: $(VERCEL_TOKEN)
      production: true
    displayName: 'Deploy Vercel'