trigger:
  - main
 
pool:
  name: Azure Pool 
 
steps:
  - task: vercel-deployment-task@1
    inputs:
      vercelProjectId: 'prj_op7yKfeX6NGXZ2nRd7X4b81P7sxB'
      vercelOrgId: $(VERCEL_ORG_ID)
      vercelToken: $(VERCEL_TOKEN)
      production: true
    displayName: 'Deploy Vercel'