trigger:
- main
 
pool:
  name: Azure Pool 

variables:
 - vercelProjectId: $(VERCEL_PROJECT_ID)
 - vercelOrgId: $(VERCEL_ORG_ID)
 - vercelToken: $(VERCEL_API_TOKEN)
 - production: true
 
jobs:
  - job: vercel
    steps:
    - script: | 
    