trigger:
  - main
 
pool:
  name: Azure Pool 
 
steps:
  - task: vercel-deployment-task@1
    inputs:
      vercelProjectId: 'prj_9AeVcqqRBFKCw6kpAbZkgIgBEZGH'
      vercelOrgId: $(VERCEL_ORG_ID)
      vercelToken: $(VERCEL_TOKEN)
      production: true
    displayName: 'Deploy Vercel'